# Generated by Django 5.2.1 on 2025-08-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactdetail_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.PositiveIntegerField(blank=True, choices=[(371, '+371 Latvia'), (372, '+372 Estonia'), (370, '+370 Lithuania')], help_text='Country dialing code without plus sign, e.g., 371', null=True)),
                ('national_number', models.CharField(blank=True, help_text='Local phone number without country code', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email address', max_length=254, null=True)),
                ('website_url', models.URLField(blank=True, help_text='Official website URL', null=True)),
                ('app_name', models.CharField(help_text="The name of your app or service, e.g. 'PetHelp'", max_length=100)),
                ('legal_name', models.CharField(help_text='The legal name of your organization or company', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('LV', 'Latvia'), ('EE', 'Estonia'), ('LT', 'Lithuania')], help_text='ISO 3166-1 alpha-2 country code', max_length=2, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('x_url', models.URLField(blank=True, null=True)),
                ('paypal_button_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Company Info',
                'verbose_name_plural': 'Company Info',
            },
        ),
        migrations.DeleteModel(
            name='ContactDetail',
        ),
    ]
