# Generated by Django 5.2.1 on 2025-08-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companyinfo_delete_contactdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
