# Generated by Django 5.2.1 on 2025-08-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_delete_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('platform', models.IntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'X'), (4, 'LinkedIn'), (5, 'YouTube'), (6, 'TikTok')])),
                ('profile_url', models.URLField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
