# Generated by Django 5.2.1 on 2025-08-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_socialmedia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmedia',
            unique_together={('content_type', 'object_id', 'platform')},
        ),
    ]
