# Generated by Django 5.2.1 on 2025-07-11 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='petsightinghistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sighting', 'verbose_name_plural': 'Sightings'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, choices=[(1, 'Young'), (2, 'Adult'), (3, 'Senior')], null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='behavior',
            field=models.IntegerField(blank=True, choices=[(1, 'Friendly'), (2, 'Aggressive'), (3, 'Calm'), (4, 'Fearful'), (5, 'Obedient')], null=True, verbose_name='Behavior'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Event Occurred At'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='final_status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Reunited with Owner'), (3, 'Given to Shelter'), (4, 'Kept by finder'), (5, 'Stray'), (6, 'Free walk'), (7, 'Found deceased'), (8, 'Pet was found by owner'), (9, 'Other')], default=1, verbose_name='Final Status'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is Closed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pattern',
            field=models.IntegerField(blank=True, choices=[(1, 'Solid'), (2, 'Striped'), (3, 'Spotted'), (4, 'Patched'), (5, 'Marbled')], null=True, verbose_name='Pattern'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image_1',
            field=models.URLField(max_length=255, verbose_name='Pet Image_1'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image_2',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Pet Image_2'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image_3',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Pet Image_3'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_image_4',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Pet Image_4'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='phone_code',
            field=models.IntegerField(blank=True, choices=[(371, 'LV (+371)'), (370, 'LT (+370)'), (372, 'EE (+372)')], null=True, verbose_name='Phone Code'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='primary_color',
            field=models.IntegerField(blank=True, choices=[(1, 'Black'), (2, 'Gray'), (3, 'White'), (4, 'Cream'), (5, 'Yellow'), (6, 'Golden'), (7, 'Brown'), (8, 'Red'), (9, 'Lilac'), (10, 'Blue'), (11, 'Green'), (12, 'Khaki'), (13, 'Beige'), (14, 'Fawn'), (15, 'Chestnut')], null=True, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='secondary_color',
            field=models.IntegerField(blank=True, choices=[(1, 'Black'), (2, 'Gray'), (3, 'White'), (4, 'Cream'), (5, 'Yellow'), (6, 'Golden'), (7, 'Brown'), (8, 'Red'), (9, 'Lilac'), (10, 'Blue'), (11, 'Green'), (12, 'Khaki'), (13, 'Beige'), (14, 'Fawn'), (15, 'Chestnut')], null=True, verbose_name='Secondary Color'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.IntegerField(choices=[(1, 'Dog'), (2, 'Cat'), (3, 'Other')], verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.IntegerField(choices=[(1, 'Lost'), (2, 'Found'), (3, 'Seen')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public?'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified?'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='pet_image',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='pet_image'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='reporter'),
        ),
        migrations.AlterField(
            model_name='petsightinghistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Found'), (2, 'Seen')], default=2, verbose_name='Status'),
        ),
    ]
