# Generated by Django 5.2.1 on 2025-07-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_pet_options_alter_petsightinghistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='name',
        ),
        migrations.AlterField(
            model_name='pet',
            name='final_status',
            field=models.IntegerField(choices=[(1, 'Unresolved'), (2, 'Reunited with Owner'), (3, 'Given to Shelter'), (4, 'Kept by finder'), (5, 'Stray'), (6, 'Free walk'), (7, 'Found deceased'), (8, 'Pet was found by owner'), (9, 'Other')], default=1, verbose_name='Final Status'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is Closed?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='phone_code',
            field=models.IntegerField(blank=True, choices=[(1, 'United States (+1)'), (31, 'Netherlands (+31)'), (33, 'France (+33)'), (34, 'Spain (+34)'), (39, 'Italy (+39)'), (41, 'Switzerland (+41)'), (44, 'United Kingdom (+44)'), (46, 'Sweden (+46)'), (48, 'Poland (+48)'), (49, 'Germany (+49)'), (370, 'Lithuania (+370)'), (371, 'Latvia (+371)'), (372, 'Estonia (+372)')], null=True, verbose_name='Phone Code'),
        ),
    ]
