# Generated by Django 5.2.1 on 2025-07-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_remove_pet_behavior_remove_pet_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='pet',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is Archived?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Phone'),
        ),
    ]
