# Generated by Django 5.2.1 on 2025-07-14 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_petshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.IntegerField(choices=[(1, 'Inappropriate content'), (2, 'Spam or misleading'), (3, 'Fake or duplicate post'), (4, 'Harassment or abuse'), (5, 'Other')], verbose_name='Report Reason')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Additional Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pets.pet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User who reported')),
            ],
            options={
                'verbose_name': 'Pet Report',
                'verbose_name_plural': 'Pet Reports',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('pet', 'user'), name='unique_user_pet_report'), models.UniqueConstraint(fields=('pet', 'ip_address'), name='unique_ip_pet_report')],
            },
        ),
    ]
