# Generated by Django 5.2.1 on 2025-07-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_petreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='reason',
        ),
    ]
