# Generated by Django 5.2.1 on 2025-07-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_remove_petreport_description_remove_petreport_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Is Banned?'),
        ),
    ]
