# Generated by Django 5.2.1 on 2025-07-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_pet_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsightinghistory',
            name='is_verified',
        ),
    ]
