# Generated by Django 5.2.1 on 2025-07-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
