# Generated by Django 5.2.1 on 2025-07-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_alter_animal_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
