# Generated by Django 5.2.1 on 2025-07-01 20:07

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the guide.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly unique identifier, autogenerated from the title.', max_length=200, unique=True)),
                ('cover', cloudinary.models.CloudinaryField(blank=True, help_text='Cover image representing the guide.', max_length=255, null=True, verbose_name='image')),
                ('cover_prompt', models.TextField(blank=True, help_text='Optional prompt or description related to the cover image.')),
                ('description', models.TextField(blank=True, help_text='Detailed description or summary of the guide.')),
                ('public', models.BooleanField(default=False, help_text='Designates whether the guide is publicly visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the guide was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the guide was last updated.')),
                ('author', models.ForeignKey(help_text='User who created the guide.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of the paragraph within the guide.')),
                ('illustration', cloudinary.models.CloudinaryField(blank=True, help_text='Optional illustrative image related to this paragraph.', max_length=255, null=True, verbose_name='image')),
                ('content', models.TextField(help_text='Text content of the paragraph.')),
                ('illustration_prompt', models.TextField(blank=True, help_text='Optional prompt or description for the illustration.')),
                ('guide', models.ForeignKey(help_text='Guide to which this paragraph belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='guides.guide')),
            ],
            options={
                'verbose_name': 'Paragraph',
                'verbose_name_plural': 'Paragraphs',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['slug'], name='guides_guid_slug_83aa9c_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['public'], name='guides_guid_public_08b6a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paragraph',
            unique_together={('guide', 'order')},
        ),
    ]
