# Generated by Django 5.2.1 on 2025-07-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='cover_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the cover image.', max_length=255),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='illustration_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the illustration.', max_length=255),
        ),
    ]
