# Generated by Django 5.2.1 on 2025-07-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_guide_cover_alt_paragraph_illustration_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='step_title',
            field=models.CharField(blank=True, help_text='Title for this step.', max_length=200),
        ),
    ]
