# Generated by Django 5.2.1 on 2025-07-24 06:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_alter_guide_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='author',
        ),
        migrations.AddField(
            model_name='guide',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this guide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guide',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this guide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the paragraph was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraph',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragraphs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the paragraph was last updated.'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragraphs_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
