# Generated by Django 5.2.1 on 2025-07-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_remove_guide_author_guide_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='cover_format',
            field=models.CharField(blank=True, help_text='Image format of the cover (e.g., jpg, png).', max_length=50),
        ),
        migrations.AddField(
            model_name='guide',
            name='cover_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height of the cover image in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='cover_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size of the cover image in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='cover_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width of the cover image in pixels.', null=True),
        ),
    ]
