# Generated by Django 5.2.1 on 2025-07-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_guide_cover_format_guide_cover_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='cover_format',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='cover_height',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='cover_size',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='cover_width',
        ),
        migrations.AddField(
            model_name='guide',
            name='cover_caption',
            field=models.CharField(blank=True, help_text='Caption or description for the cover image.', max_length=255),
        ),
        migrations.AddField(
            model_name='guide',
            name='cover_source',
            field=models.CharField(blank=True, help_text='Source or credit for the cover image.', max_length=255),
        ),
        migrations.AddField(
            model_name='guide',
            name='image_format',
            field=models.CharField(blank=True, help_text='Image format (e.g., jpg, png).', max_length=50),
        ),
        migrations.AddField(
            model_name='guide',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='image_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='image_format',
            field=models.CharField(blank=True, help_text='Image format (e.g., jpg, png).', max_length=50),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='image_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels.', null=True),
        ),
    ]
