# Generated by Django 5.2.1 on 2025-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_remove_guide_image_format_remove_guide_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='illustration_caption',
            field=models.CharField(blank=True, help_text='Caption or description for the illustration.', max_length=255),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='illustration_format',
            field=models.CharField(blank=True, help_text='Image format of the illustration (e.g., jpg, png).', max_length=50),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='illustration_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height of the illustration in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='illustration_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size of the illustration in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='illustration_source',
            field=models.CharField(blank=True, help_text='Source or credit for the illustration.', max_length=255),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='illustration_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width of the illustration in pixels.', null=True),
        ),
    ]
