# Generated by Django 5.2.1 on 2025-07-24 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0009_paragraph_illustration_caption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guide',
            name='guides_guid_public_08b6a3_idx',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='public',
            new_name='is_public',
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['is_public'], name='guides_guid_is_publ_dbf718_idx'),
        ),
    ]
