# Generated by Django 5.2.1 on 2025-07-26 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0010_remove_guide_guides_guid_public_08b6a3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guide',
            name='guides_guid_is_publ_dbf718_idx',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='is_public',
            new_name='is_visible',
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['is_visible'], name='guides_guid_is_visi_61844a_idx'),
        ),
    ]
