# Generated by Django 5.2.1 on 2025-08-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0011_remove_guide_guides_guid_is_publ_dbf718_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='cover_format',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='cover_height',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='cover_size',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='cover_width',
        ),
        migrations.AddField(
            model_name='guide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the guides.'),
            preserve_default=False,
        ),
    ]
