# Generated by Django 5.2.1 on 2025-08-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0012_remove_guide_cover_format_remove_guide_cover_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='illustration_format',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='illustration_height',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='illustration_size',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='illustration_width',
        ),
        migrations.AlterField(
            model_name='guide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the guides.'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the paragraph within the guide.'),
        ),
    ]
