# Generated by Django 5.2.1 on 2025-08-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0013_alter_guide_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='order',
            field=models.PositiveIntegerField(help_text='Order of the guides.'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='order',
            field=models.PositiveIntegerField(help_text='Order of the paragraph within the guide.'),
        ),
    ]
