# Generated by Django 5.2.1 on 2025-07-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_updated_at_alter_feedback_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='created_by',
        ),
    ]
