# Generated by Django 5.2.1 on 2025-08-07 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_user_feedback_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sender',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='John', help_text='Enter your full name.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the feedback was created.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Enter your email address so we can get back to you.', max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(help_text='Write your feedback message here.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.PositiveSmallIntegerField(choices=[(1, 'General Questions'), (2, 'Bug Report'), (3, 'Feature Request'), (4, 'Collaboration Request'), (5, 'Other')], default=1, help_text='Choose the topic that best describes your feedback.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the feedback was last updated.'),
        ),
    ]
