# Generated by Django 5.2.1 on 2025-08-16 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_sender_feedback_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='The testimonial content.')),
                ('author_name', models.CharField(help_text='Full name of the person.', max_length=255)),
                ('author_title', models.CharField(blank=True, help_text='Job title of the person.', max_length=255)),
                ('author_company', models.CharField(blank=True, help_text='Company name.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the testimonial was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the testimonial was last updated.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
