# Generated by Django 5.2.1 on 2025-08-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible to public'),
        ),
    ]
