# Generated by Django 5.2.1 on 2025-07-17 15:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0003_shelter_accepts_donations_shelter_accepts_volunteers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='shelter',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cover image representing the guide.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='cover_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the cover image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone_code',
            field=models.IntegerField(blank=True, choices=[(1, 'United States (+1)'), (31, 'Netherlands (+31)'), (33, 'France (+33)'), (34, 'Spain (+34)'), (39, 'Italy (+39)'), (41, 'Switzerland (+41)'), (44, 'United Kingdom (+44)'), (46, 'Sweden (+46)'), (48, 'Poland (+48)'), (49, 'Germany (+49)'), (370, 'Lithuania (+370)'), (371, 'Latvia (+371)'), (372, 'Estonia (+372)')], null=True, verbose_name='Phone Code'),
        ),
    ]
