# Generated by Django 5.2.1 on 2025-07-17 22:06

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0004_remove_shelter_phone_number_shelter_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='social_media',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='shelter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='shelters.shelter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelter',
            name='accepts_donations',
            field=models.BooleanField(default=False, verbose_name='Accepts donations'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='accepts_volunteers',
            field=models.BooleanField(default=False, verbose_name='Accepts volunteers'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Municipal Shelter'), (2, 'Animal Rescue'), (3, 'Sanctuary'), (4, 'Private Shelter'), (5, 'Other')], null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='country',
            field=models.CharField(blank=True, choices=[('LV', 'Latvija'), ('EE', 'Igaunija'), ('LT', 'Lietuva')], max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cover image representing the shelter.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='full_address',
            field=models.TextField(blank=True, null=True, verbose_name='Full address'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Open to public'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='offers_adoption',
            field=models.BooleanField(default=False, verbose_name='Offers adoption'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='size',
            field=models.IntegerField(blank=True, choices=[(1, 'Small (1-20 animals)'), (2, 'Medium (21-100 animals)'), (3, 'Large (100+ animals)')], null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'X'), (4, 'LinkedIn'), (5, 'YouTube'), (6, 'TikTok'), (7, 'Pinterest'), (8, 'Snapchat')], verbose_name='Platform'),
        ),
    ]
