# Generated by Django 5.2.1 on 2025-07-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0005_remove_shelter_social_media_socialmedia_shelter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='shelter',
        ),
        migrations.AddField(
            model_name='shelter',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='shelters', to='shelters.socialmedia', verbose_name='Social media'),
        ),
    ]
