# Generated by Django 5.2.1 on 2025-07-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0006_remove_socialmedia_shelter_shelter_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='social_media',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='shelters.shelter'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmedia',
            unique_together={('shelter', 'platform')},
        ),
    ]
