# Generated by Django 5.2.1 on 2025-07-17 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0007_remove_shelter_social_media_socialmedia_shelter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='shelters.shelter'),
        ),
    ]
