# Generated by Django 5.2.1 on 2025-07-18 11:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0008_alter_socialmedia_shelter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaltype',
            options={'verbose_name': 'Animal type', 'verbose_name_plural': 'Animal types'},
        ),
        migrations.AddField(
            model_name='shelter',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Logo image representing the shelter.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='logo_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the logo image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Animal type'),
        ),
    ]
