# Generated by Django 5.2.1 on 2025-07-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0009_alter_animaltype_options_shelter_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaltype',
            name='slug',
            field=models.SlugField(blank=True, help_text='Stable, URL-safe code for this animal type (auto-generated)'),
        ),
    ]
