# Generated by Django 5.2.1 on 2025-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0010_animaltype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaltype',
            name='slug',
        ),
        migrations.AlterField(
            model_name='shelter',
            name='logo_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the togo image.', max_length=255),
        ),
    ]
