# Generated by Django 5.2.1 on 2025-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0011_remove_animaltype_slug_alter_shelter_logo_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaltype',
            name='slug',
            field=models.SlugField(blank=True, help_text='Stable, URL-safe code for this animal type (auto-generated)', unique=True),
        ),
    ]
