# Generated by Django 5.2.1 on 2025-07-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0012_animaltype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaltype',
            name='slug',
        ),
    ]
