# Generated by Django 5.2.1 on 2025-07-23 17:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0014_animaltype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
