# Generated by Django 5.2.1 on 2025-07-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0016_remove_shelter_full_address_remove_shelter_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='phone_code',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='website',
        ),
        migrations.AddField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number including country code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official website URL', null=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email address', max_length=254, null=True),
        ),
    ]
