# Generated by Django 5.2.1 on 2025-07-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0017_remove_shelter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='country_code',
            field=models.PositiveIntegerField(blank=True, choices=[(371, '+371 Latvia'), (372, '+372 Estonia'), (370, '+370 Lithuania')], help_text='Country dialing code without plus sign, e.g., 371', null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='national_number',
            field=models.CharField(blank=True, help_text='Local phone number without country code', max_length=15, null=True),
        ),
    ]
