# Generated by Django 5.2.1 on 2025-07-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0018_remove_shelter_phone_number_shelter_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='phone_number',
        ),
    ]
