# Generated by Django 5.2.1 on 2025-07-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0019_remove_shelter_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='country_code',
            new_name='country_codex',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='national_number',
            new_name='national_numberx',
        ),
    ]
