# Generated by Django 5.2.1 on 2025-07-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0020_rename_country_code_shelter_country_codex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='country_codex',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='national_numberx',
            new_name='national_number',
        ),
    ]
