# Generated by Django 5.2.1 on 2025-07-26 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0021_rename_country_codex_shelter_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelter',
            options={'ordering': ['operating_name'], 'verbose_name': 'Shelter', 'verbose_name_plural': 'Shelters'},
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='accepts_donations',
            new_name='is_accepting_donations',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='accepts_volunteers',
            new_name='is_accepting_volunteers',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='offers_adoption',
            new_name='is_offering_adoption',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='logo_alt',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='name',
        ),
        migrations.AddField(
            model_name='shelter',
            name='cover_caption',
            field=models.CharField(blank=True, help_text='Caption or description for the shelter image.', max_length=255),
        ),
        migrations.AddField(
            model_name='shelter',
            name='cover_format',
            field=models.CharField(blank=True, help_text='Image format of the shelter (e.g., jpg, png).', max_length=50),
        ),
        migrations.AddField(
            model_name='shelter',
            name='cover_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height of the shelter image in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='cover_prompt',
            field=models.TextField(blank=True, help_text='Optional prompt or description related to the shelter image.'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='cover_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size of the shelter image in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='cover_source',
            field=models.CharField(blank=True, help_text='Source or credit for the shelter image.', max_length=255),
        ),
        migrations.AddField(
            model_name='shelter',
            name='cover_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width of the shelter image in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the shelter was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this shelter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelters_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelter',
            name='established_at',
            field=models.DateField(blank=True, null=True, verbose_name='Established Date'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible to public'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal entity Name'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='operating_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operating Name'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='registration_number',
            field=models.CharField(default=123, max_length=100, unique=True, verbose_name='Registration Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the shelter was last updated.'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this shelter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelters_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Municipal Shelter'), (2, 'Animal Rescue'), (3, 'Sanctuary'), (4, 'Private Shelter')], null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='cover_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the shelter image.', max_length=255),
        ),
    ]
