# Generated by Django 5.2.1 on 2025-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0023_alter_shelter_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='registration_number',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Registration Number'),
            preserve_default=False,
        ),
    ]
