# Generated by Django 5.2.1 on 2025-07-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0024_alter_shelter_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Registration Number'),
        ),
    ]
