# Generated by Django 5.2.1 on 2025-07-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0025_alter_shelter_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'X'), (4, 'LinkedIn'), (5, 'YouTube'), (6, 'TikTok')], verbose_name='Platform'),
        ),
    ]
