# Generated by Django 5.2.1 on 2025-07-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0026_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='cover_format',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='cover_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='cover_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='cover_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
