# Generated by Django 5.2.1 on 2025-07-31 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0027_alter_shelter_cover_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cover image.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
