# Generated by Django 5.2.1 on 2025-07-31 16:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0028_alter_shelter_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='cover_format',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='cover_height',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='cover_size',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='cover_width',
        ),
        migrations.AlterField(
            model_name='shelter',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cover image representing the shelter.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
