# Generated by Django 5.2.1 on 2025-07-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0029_remove_shelter_cover_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='is_official',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='is_verified',
        ),
    ]
