# Generated by Django 5.2.1 on 2025-08-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0030_remove_socialmedia_is_official_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
