# Generated by Django 5.2.1 on 2025-07-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_provider_type_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.IntegerField(choices=[(1, 'Sitting'), (2, 'Walking'), (3, 'Grooming'), (4, 'Training'), (5, 'Boarding'), (6, 'Veterinary'), (7, 'Photography'), (8, 'Rescue'), (9, 'Supplies'), (10, 'Art'), (11, 'Burial'), (12, 'Transport'), (13, 'Breeders'), (14, 'Insurance'), (15, 'Miscellaneous')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_type',
            field=models.IntegerField(choices=[(1, 'Per Hour'), (2, 'Per Unit'), (3, 'Per Day'), (4, 'By Agreement')], default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.IntegerField(choices=[(1, 'Individual'), (2, 'Company')]),
        ),
    ]
