# Generated by Django 5.2.1 on 2025-07-16 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_category_alter_service_price_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Is Banned?'),
        ),
        migrations.CreateModel(
            name='ServiceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User who shared')),
            ],
            options={
                'verbose_name': 'Service Share',
                'verbose_name_plural': 'Service Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User who viewed')),
            ],
            options={
                'verbose_name': 'Service View',
                'verbose_name_plural': 'Service Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User who reported')),
            ],
            options={
                'verbose_name': 'Service Report',
                'verbose_name_plural': 'Service Reports',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('service', 'user'), name='unique_user_service_report'), models.UniqueConstraint(fields=('service', 'ip_address'), name='unique_ip_service_report')],
            },
        ),
    ]
