# Generated by Django 5.2.1 on 2025-07-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_workinghour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='phone_code',
        ),
        migrations.RemoveField(
            model_name='service',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='service',
            name='website',
        ),
        migrations.AddField(
            model_name='service',
            name='country_code',
            field=models.PositiveIntegerField(blank=True, choices=[(371, '+371 Latvia'), (372, '+372 Estonia'), (370, '+370 Lithuania')], help_text='Country dialing code without plus sign, e.g., 371', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='national_number',
            field=models.CharField(blank=True, help_text='Local phone number without country code', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official website URL', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email address', max_length=254, null=True),
        ),
    ]
