# Generated by Django 5.2.1 on 2025-07-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_phone_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='established_at',
            field=models.DateField(blank=True, null=True, verbose_name='Established Date'),
        ),
        migrations.AddField(
            model_name='service',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal entity Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='operating_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operating Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Registration Number'),
        ),
    ]
