# Generated by Django 5.2.1 on 2025-07-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_title_service_established_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'X'), (4, 'LinkedIn'), (5, 'YouTube'), (6, 'TikTok'), (7, 'Pinterest'), (8, 'Snapchat')], verbose_name='Platform')),
                ('profile_url', models.URLField()),
                ('is_official', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='services.service')),
            ],
            options={
                'unique_together': {('service', 'platform')},
            },
        ),
    ]
