# Generated by Django 5.2.1 on 2025-07-27 09:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.RemoveField(
            model_name='location',
            name='street',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, choices=[('LV', 'Latvia'), ('EE', 'Estonia'), ('LT', 'Lithuania')], help_text='ISO 3166-1 alpha-2 country code', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='location',
            name='state_or_province',
            field=models.CharField(blank=True, help_text='State, province, or region', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address, P.O. box, company name, c/o', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='street_address2',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
