# Generated by Django 5.2.1 on 2025-07-27 12:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_location_full_address_remove_location_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cover image representing the shelter.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the shelter image.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_caption',
            field=models.CharField(blank=True, help_text='Caption or description for the shelter image.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_format',
            field=models.CharField(blank=True, help_text='Image format of the shelter (e.g., jpg, png).', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height of the shelter image in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_prompt',
            field=models.TextField(blank=True, help_text='Optional prompt or description related to the shelter image.'),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size of the shelter image in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_source',
            field=models.CharField(blank=True, help_text='Source or credit for the shelter image.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width of the shelter image in pixels.', null=True),
        ),
    ]
