# Generated by Django 5.2.1 on 2025-07-28 20:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_service_created_by_service_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cover image representing the service.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the service image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_caption',
            field=models.CharField(blank=True, help_text='Caption or description for the service image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_format',
            field=models.CharField(blank=True, help_text='Image format of the service (e.g., jpg, png).', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height of the service image in pixels.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_prompt',
            field=models.TextField(blank=True, help_text='Optional prompt or description related to the service image.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size of the service image in bytes.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_source',
            field=models.CharField(blank=True, help_text='Source or credit for the service image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width of the service image in pixels.', null=True),
        ),
    ]
