# Generated by Django 5.2.1 on 2025-08-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_service_cover_alter_service_cover_alt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cover_format',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cover_height',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cover_size',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cover_width',
        ),
    ]
