# Generated by Django 5.2.1 on 2025-08-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_service_cover_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image_1',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Servisa 1. attēls'),
        ),
    ]
