# Generated by Django 5.2.1 on 2025-08-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_service_service_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'X'), (4, 'LinkedIn'), (5, 'YouTube'), (6, 'TikTok')], verbose_name='Platform'),
        ),
    ]
