# Generated by Django 5.2.1 on 2025-08-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Service category')),
                ('slug', models.SlugField(blank=True, help_text='Stable, URL-safe code for this service category (auto-generated)', unique=True)),
            ],
            options={
                'verbose_name': 'Service category',
                'verbose_name_plural': 'Service categories',
            },
        ),
    ]
