# Generated by Django 5.2.1 on 2025-08-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_servicecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='service_categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.servicecategory', verbose_name='Service categories'),
        ),
    ]
