# Generated by Django 5.2.1 on 2025-08-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pettype',
            options={'ordering': ['name']},
        ),
    ]
